[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

# API redirect
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

# âœ… React SPA routing (MOST IMPORTANT)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
